### ISSUE TITLE
Script fails with KeyError: 'bkp_storage_account' 

### ISSUE THREAD

**Issue by tomconte** [Azure/azfilebackup#16]
if the TAG 'bkp_storage_account' does not exist,
script musts report this fact somehow and compose the storage-account name
with known naming-convention.
 
But it throws an error message and exit:

```
hec45v101770:/usr/sap/backup # /usr/share/python/bin/azfilebak -x
Traceback (most recent call last):
  File "/usr/share/python/bin/azfilebak", line 11, in <module>
    sys.exit(main())
  File "/usr/share/python/lib/python2.7/site-packages/azfilebak/__main__.py", line 15, in main
    Runner.main()
  File "/usr/share/python/lib/python2.7/site-packages/azfilebak/runner.py", line 173, in main
    for line in backup_agent.get_configuration_printable(output_dir=output_dir):
  File "/usr/share/python/lib/python2.7/site-packages/azfilebak/backupagent.py", line 414, in get_configuration_printable
    "azure_storage_account_name:         {}".format(self.backup_configuration.get_azure_storage_account_name())
  File "/usr/share/python/lib/python2.7/site-packages/azfilebak/backupconfiguration.py", line 173, in get_azure_storage_account_name
    account = self.instance_metadata.get_tags()['bkp_storage_account']
KeyError: 'bkp_storage_account'
```

**Comment by tomconte** [comment]
Fixed in #17.
